baseURL = 'http://example.org/'
languageCode = 'FR-fr'
title = 'Geoffrey'
theme = "cactus"

[params]
  description = "Idée en vrac, des fois tech, des fois expérience, des fois explication, au-delà de partager mes découvertes, ça me permet aussi de m’en souvenir."
  showAllPostsOnHomePage = true
  postsOnHomePage = 5 # this option will be ignored

  tagsOverview = true

# table des matières
  tocInline = true

  showProjectsList = true
  projectsUrl = "https://github.com/Attadeurtia"

  rss = true

[[params.social]]
  name = "github"
  link = "https://github.com/Attadeurtia"

[[params.social]]
  name = "email"
  link = "geoffreypose@gmail.com" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "linkedin.com/in/geoffrey-pos%C3%A9-299709200/"

