baseURL = "https://attadeurtia.github.io/blog/"
languageCode = "fr-fr"
title = "Geoffrey"
theme = 'ananke'
copyright = "© Geoffrey"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


pagination.pagerSize=3 # articles per page

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Bienvenue sur mon blog ! Étudiant touche à tout, ce site est un lieu libre de partage d’experiences, de tuto et de découvertes sur tout et rien."
#	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

  [params.services]
    [params.services.umami_analytics]
      id = '8261e837-91d2-433d-ba96-be0441457e4a'
      script_url = 'https://cloud.umami.is/script.js'


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Attadeurtia"

[[params.social]]
name = "Mastodon"
icon = "Mastodon"
url = "https://social.vivaldi.net/@Attadeurtia"



# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[module]  
  [[module.imports]]  
    path = 'github.com/hugomods/umami-analytics'